# Generated by Django 5.2.6 on 2025-09-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='watched_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
