# Generated by Django 5.2.6 on 2025-09-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
